//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public Nullable<int> OIDKey { get; set; }
        public string Value { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> WMIID { get; set; }
        public string IPAddress { get; set; }
    
        public virtual OID OID { get; set; }
        public virtual WMI WMI { get; set; }
    }
}
