//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace snmp_client.WebTimerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.theknot.com/Time", ConfigurationName="WebTimerService.GetCurrentTimeSoap")]
    public interface GetCurrentTimeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.theknot.com/Time/currentTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string currentTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.theknot.com/Time/currentTime", ReplyAction="*")]
        System.Threading.Tasks.Task<string> currentTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetCurrentTimeSoapChannel : snmp_client.WebTimerService.GetCurrentTimeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentTimeSoapClient : System.ServiceModel.ClientBase<snmp_client.WebTimerService.GetCurrentTimeSoap>, snmp_client.WebTimerService.GetCurrentTimeSoap {
        
        public GetCurrentTimeSoapClient() {
        }
        
        public GetCurrentTimeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetCurrentTimeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCurrentTimeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetCurrentTimeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string currentTime() {
            return base.Channel.currentTime();
        }
        
        public System.Threading.Tasks.Task<string> currentTimeAsync() {
            return base.Channel.currentTimeAsync();
        }
    }
}
